//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunty.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hunty.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Company.
        /// </summary>
        internal static string ButtonGrandCompany {
            get {
                return ResourceManager.GetString("ButtonGrandCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string ButtonJobs {
            get {
                return ResourceManager.GetString("ButtonJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord:.
        /// </summary>
        internal static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Thread.
        /// </summary>
        internal static string DiscordThread {
            get {
                return ResourceManager.GetString("DiscordThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job is done with the hunting log..
        /// </summary>
        internal static string ErrorLogDone {
            get {
                return ResourceManager.GetString("ErrorLogDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character does not have a Grand Company..
        /// </summary>
        internal static string ErrorNoGrandCompany {
            get {
                return ResourceManager.GetString("ErrorNoGrandCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job has no hunting log..
        /// </summary>
        internal static string ErrorNoLog {
            get {
                return ResourceManager.GetString("ErrorNoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string GithubIssues {
            get {
                return ResourceManager.GetString("GithubIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a small guide book..
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a big guide book with hunts grouped by area..
        /// </summary>
        internal static string HelpMessageCompanion {
            get {
                return ResourceManager.GetString("HelpMessageCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a big guide book..
        /// </summary>
        internal static string HelpMessageXL {
            get {
                return ResourceManager.GetString("HelpMessageXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ko-Fi Tip.
        /// </summary>
        internal static string KoFiTip {
            get {
                return ResourceManager.GetString("KoFiTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide finished entries.
        /// </summary>
        internal static string OptionSkipDone {
            get {
                return ResourceManager.GetString("OptionSkipDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string SelectorRank {
            get {
                return ResourceManager.GetString("SelectorRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coords.
        /// </summary>
        internal static string TableLabelCoords {
            get {
                return ResourceManager.GetString("TableLabelCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TableLabelDone {
            get {
                return ResourceManager.GetString("TableLabelDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon.
        /// </summary>
        internal static string TableLabelDungeon {
            get {
                return ResourceManager.GetString("TableLabelDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string TableLabelMonster {
            get {
                return ResourceManager.GetString("TableLabelMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
